[package]
name = "pq"
version = "0.1.0"
edition = "2024"

[dependencies]

# Command line interfaces
clap = { version = "4.5.51", features = ["derive"] }

# Cross platform terminal handling and TUI library and allows for raw-mode
# terminal for unbuffered STDIN
crossterm = "0.29.0"

# Error propagation and wrapper types
thiserror = "2.0.17"

# For
libc = "0.2"

# The library to beat internally
serde_json = { version = "1.0.145", features = ["preserve_order"] }

# Python-like query engine
# starlark = "0.13.0"

# Used for boilerplate like enum variant names
strum = { version = "0.27.2", features = ["derive", "strum_macros"] }
strum_macros = { version = "0.27.2" }
smallvec = "1.15.1"

# Used by the ui_json_token_rows to open a beautiful HTML UI in the browser
open = "5.3.3"
memmap2 = "0.9.10"

# TODO: For adding Rust extension types into Starlark
# allocative = "0.3.4"
# starlark_derive = "0.13.0"
# derive_more = { version = "2.0.1", features = ["display"] }

# Asynchronous runtime and file system IO utilities
[dependencies.tokio]
version = "1.48.0"
default-features = false
features = [
    "rt",              # the runtime itself
    "rt-multi-thread", # use rt for a single-threaded runtime
    "fs",              # file I/O
    "io-std",          # stdin/stdout
    "io-util",         # general io
    "sync",            # mpsc, oneshot, Mutex, RwLock
    "macros",          # tokio::main
    "time",
]

[features]
default = []
implicit_row_ids = []
store_heap_strs = []
# log_n_indentation = []

# To have any features type checked by VS Code, add a .vscode/settings.json:
# {
#     "rust-analyzer.cargo.features": [
#         "query-engine-pyo3",
#         "query-parser-rustpython"
#     ]
# }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
